# Generated by Django 5.2.8 on 2025-12-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_assigned_by_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
