# Generated by Django 5.2.8 on 2025-12-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_userprofile_role_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='tasks/'),
        ),
    ]
