# Generated by Django 4.2.27 on 2026-01-29 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_profile"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="task",
            table="app_task",
        ),
    ]
