# Generated by Django 5.2.8 on 2026-01-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_task_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="task",
            table=None,
        ),
    ]
